import React from 'react';
import { SleepLog } from '../types';
import { format } from 'date-fns';
import { Download } from 'lucide-react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface Props {
  logs: SleepLog[];
}

export default function PDFExport({ logs }: Props) {
  const generatePDF = () => {
    if (logs.length === 0) {
      alert('No sleep logs to export. Add some logs first!');
      return;
    }

    const doc = new jsPDF('p', 'mm', 'a4');
    const pageWidth = doc.internal.pageSize.getWidth();

    // Title
    doc.setFontSize(22);
    doc.setTextColor(99, 102, 241);
    doc.text('SleepWell Report', pageWidth / 2, 20, { align: 'center' });

    // Date
    doc.setFontSize(11);
    doc.setTextColor(100, 116, 139);
    doc.text(`Generated: ${format(new Date(), 'MMMM do, yyyy')}`, pageWidth / 2, 30, { align: 'center' });

    // Summary Stats
    const totalLogs = logs.length;
    const avgQuality = totalLogs > 0
      ? (logs.reduce((sum, log) => sum + log.quality, 0) / totalLogs).toFixed(1)
      : '0';
    
    const avgDuration = totalLogs > 0
      ? (logs.reduce((sum, log) => {
          const start = log.startTime.toDate();
          const end = log.endTime.toDate();
          const duration = (end.getTime() - start.getTime()) / (1000 * 60 * 60);
          return sum + duration;
        }, 0) / totalLogs).toFixed(1)
      : '0';

    // Stats box
    doc.setDrawColor(99, 102, 241);
    doc.setLineWidth(0.5);
    doc.rect(20, 40, pageWidth - 40, 40);
    
    doc.setFontSize(12);
    doc.setTextColor(51, 65, 85);
    doc.text('📊 Sleep Summary', 30, 52);
    
    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139);
    doc.text(`Total Logs: ${totalLogs}`, 30, 62);
    doc.text(`Average Quality: ${avgQuality} / 5`, 80, 62);
    doc.text(`Average Duration: ${avgDuration}h`, 140, 62);

    // Table
    const tableData = logs.slice(0, 30).map(log => {
      const start = log.startTime.toDate();
      const end = log.endTime.toDate();
      const duration = ((end.getTime() - start.getTime()) / (1000 * 60 * 60)).toFixed(1);
      return [
        format(start, 'MMM dd, yyyy'),
        format(start, 'h:mm a'),
        format(end, 'h:mm a'),
        `${duration}h`,
        `${log.quality}/5`,
        log.mood || 'N/A'
      ];
    });

    autoTable(doc, {
      head: [['Date', 'Bedtime', 'Wake Time', 'Duration', 'Quality', 'Mood']],
      body: tableData,
      startY: 90,
      theme: 'striped',
      headStyles: {
        fillColor: [99, 102, 241],
        textColor: [255, 255, 255],
        fontSize: 10,
        fontStyle: 'bold',
      },
      styles: {
        fontSize: 9,
        cellPadding: 3,
      },
      columnStyles: {
        0: { cellWidth: 35 },
        1: { cellWidth: 30 },
        2: { cellWidth: 30 },
        3: { cellWidth: 25 },
        4: { cellWidth: 25 },
        5: { cellWidth: 35 },
      },
    });

    // Footer
    const finalY = (doc as any).lastAutoTable?.finalY || 200;
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text(
      `Generated by SleepWell - ${totalLogs} logs included. ${totalLogs > 30 ? 'Showing latest 30 logs.' : ''}`,
      pageWidth / 2,
      finalY + 15,
      { align: 'center' }
    );

    // Save the PDF
    doc.save(`SleepWell-Report-${format(new Date(), 'yyyy-MM-dd')}.pdf`);
  };

  return (
    <button
      onClick={generatePDF}
      disabled={logs.length === 0}
      className={`w-full py-3 rounded-xl font-medium transition-all flex items-center justify-center gap-2 ${
        logs.length > 0
          ? 'bg-indigo-600 hover:bg-indigo-700 text-white shadow-lg shadow-indigo-900/30'
          : 'bg-white/5 text-slate-500 cursor-not-allowed'
      }`}
    >
      <Download className="w-5 h-5" />
      Export PDF
      {logs.length > 0 && (
        <span className="text-xs bg-white/20 px-2 py-0.5 rounded-full">
          {logs.length}
        </span>
      )}
    </button>
  );
}